# Generated by Django 3.2.6 on 2021-08-05 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bid',
            field=models.IntegerField(default=1, verbose_name='bid'),
        ),
        migrations.AddField(
            model_name='member',
            name='lastPropose',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='lastPropose'),
            preserve_default=False,
        ),
    ]
