# Generated by Django 3.1.7 on 2021-05-12 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('url', models.TextField(verbose_name='url')),
                ('is_scraped', models.IntegerField(default=0, verbose_name='is_scraped')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='registered_at')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['registered_at'],
            },
        ),
    ]
